### ISSUE TITLE
全文検索の調査

### ISSUE THREAD

**Issue by kanedaq** [qin-team-recipe/03-recipe-app-backend#18]
## どうやって実装するのか
- [PGroonga](https://pgroonga.github.io/ja/)を使ってみた
  - Qiitaの記事にするほどでもなかったので、こちらに試した手順を書きます

## Docker
- 手元のdocker-compose.yamlを1行変更しただけで動いた。
変更前：`image: postgres`
変更後：`image: groonga/pgroonga:3.0.8-alpine-15-slim`

## DB側で試す
- [チュートリアル](https://pgroonga.github.io/ja/tutorial/)通りにmemosテーブルを作成し、以下のクエリーを発行。→普通に動いた
`SELECT * FROM memos WHERE content &@ '全文検索';`

## sqlcで試す
- 以下のSQLを設定してAPIを作ってみた。→普通に動いた
`-- name: ListMemo :many`
`SELECT * FROM memos WHERE content &@ '全文検索';`

![pgroonga](https://github.com/qin-team-recipe/03-recipe-app-backend/assets/51765169/e7e6febf-6caa-4583-a81d-75842f543192)

**Comment by aopontann** [comment]
### メモ
- [PostgreSQL の拡張機能を構成する](https://cloud.google.com/sql/docs/postgres/extensions?hl=ja)
- [PostgreSQLで日本語全文検索 - LIKEとpg_bigmとPGroonga](https://www.clear-code.com/blog/2015/5/25.html)
