### ISSUE TITLE
マイグレーションツールの選定

### ISSUE THREAD

**Issue by aopontann** [qin-team-recipe/03-recipe-app-backend#2]
https://docs.sqlc.dev/en/stable/howto/ddl.html

**Comment by takutok28** [comment]
この表見る感じだと、golang migrate かAtlasのどちらかが良さそうで、
王道をいくならgolang migrate
リッチな機能を使いたいならAtlasって感じですね！
https://atlasgo.io/blog/2022/12/01/picking-database-migration-tool

**Comment by aopontann** [comment]
ありがとうございます！
確認してみます

**Comment by aopontann** [comment]
> この表見る感じだと、golang migrate かAtlasのどちらかが良さそうで、 王道をいくならgolang migrate リッチな機能を使いたいならAtlasって感じですね！ https://atlasgo.io/blog/2022/12/01/picking-database-migration-tool

Atlasを使ってみようと思います！
