### ISSUE TITLE
atlasでnanoid関数が使えない現象について

### ISSUE THREAD

**Issue by aopontann** [qin-team-recipe/03-recipe-app-backend#20]
## バグの実現方法
1. README.mdに記載してあるマイグレーションのコマンドを実行する

## なぜこの変更が必要なのか
- atlasでデータベースのテーブルを作成するため

## どうやって実装するのか
- Atlasの[Manual Migrations](https://atlasgo.io/versioned/new#custom-statements-delimiter)を参考

**Comment by aopontann** [comment]
nanoidを使えるようにする[SQL](https://github.com/viascom/nanoid-postgres/blob/main/nanoid.sql)を
```
-- atlas:delimiter -- end

CREATE EXTENSION ...

-- end
```
このようにデミリタを設定することでエラーは解消された

**Comment by aopontann** [comment]
schema.sqlを修正し、マイグレーションの実行をしたが、別のエラーが発生するようになった
```
Error: create "shopping_list" table: pq: type "type_shopping_item[]" does not exist
```

**Comment by aopontann** [comment]
### 今後の進め方
- Atlasを使うのを止めて、別のマイグレーションツールを使う
- マイグレーションツールを使わない(psqlでSQL直打ち)
- CREATE TYPE 文を使わないテーブル設計にする

**Comment by kanedaq** [comment]
全文検索のPGroongaも使いたいので、schema.sqlに以下のSQLも加えてお試しお願いします。


[チュートリアル](https://pgroonga.github.io/ja/tutorial/)より
```
CREATE TABLE memos (
  id integer,
  content text
);

CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE INDEX pgroonga_content_index ON memos USING pgroonga (content);

SET enable_seqscan = off;
```

**Comment by kanedaq** [comment]
CREATE TYPEが直接実行できない場合、以下のようにCREATE TYPEを行うストアドプロシージャを作って実行するのも試してほしいです。

```
CREATE OR REPLACE PROCEDURE create_type()
    LANGUAGE plpgsql
AS
$$
BEGIN
    CREATE TYPE type_shopping_item AS (
        item VARCHAR,
        is_on BOOLEAN
    );
END
$$;

CALL create_type();
```

**Comment by aopontann** [comment]
> CREATE TYPEが直接実行できない場合、以下のようにCREATE TYPEを行うストアドプロシージャを作って実行するのも試してほしいです。
> 
> ```
> CREATE OR REPLACE PROCEDURE create_type()
>     LANGUAGE plpgsql
> AS
> $$
> BEGIN
>     CREATE TYPE type_shopping_item AS (
>         item VARCHAR,
>         is_on BOOLEAN
>     );
> END
> $$;
> 
> CALL create_type();
> ```

ありがとうございます！
試してみます

**Comment by aopontann** [comment]
@kanedaq さん
すみません _(._.)_
前回のミーティングのとき、nanoidが使えるようになったと言いましたが、
何故かまた使えなくなってしまいました...
この原因についていろいろ調べたのですが、解決できなかったです。
@kanedaq さんが提案してくださったストアドプロシージャも試しましたが、ダメでした...

なので一旦、Atlasを使うのを止めようと思います。
今後は別のマイグレーションを使うかマイグレーションを使わずに行くか少し相談したいです。

**Comment by aopontann** [comment]
@kanedaq さん
Atlasを使うのを止めた理由は他にもあります。
それは、`開発環境を動かすのに2コアのCPUではスペックが足りなくなった`からです。

詳しく説明すると、
- GoCVをインストールしてから、Codespacesが立ち上がらくなることがあったため、運よく立ち上がったときにCPU使用率を調べた結果、CPU使用率がほぼマックスになっていた
- Atlasを使うのにDocker環境が必要で、Dockerが割とCPUのリソースを消費していると思う
- CPUを4コアに増やしてもいいが、無料枠で使える時間が30時間になってしまう

これらの理由があったため、Atlasを使うのを止めようと考えました。

意見など何でもいいので何かあればメッセージお願いします！

**Comment by kanedaq** [comment]
@aopontann 
ありがとうございます！
お手数をお掛けしております。使ってみないと分からないことが多いですね。

あおさんから教えていただいたRealWorldで、golang-migrateが使われていたので、一度試してみたい気がしますね。
これがダメなら、マイグレーションを使わない方向かなぁ。

GoCVの件は、次回のミーティングでちょっとお話したいです。
よろしくお願いいたします。

**Comment by aopontann** [comment]
@kanedaq 
承知しました！
golang-migrate使えるようにしました！
