### ISSUE TITLE
issueを作成したとき、自動でbackendラベルを付けるようにしたい

### ISSUE THREAD

**Issue by aopontann** [qin-team-recipe/03-recipe-app-backend#4]
### 参考になりそうなサイト
- [Issue にラベルを追加する](https://docs.github.com/ja/actions/managing-issues-and-pull-requests/adding-labels-to-issues)

**Comment by takutok28** [comment]
これやっちゃいますね。issue_templateごとにラベルを決めておいてgithub_actionsに明示的に記述すると、そのテンプレートを使った際にラベルが追加される認識で合っていますか?
どのラベルを使うか決める必要がありそうですね！
機能実装→enhancement, backend
バグ修正→bug, backend 
って感じでどうしょうか！

**Comment by aopontann** [comment]
issueを作成したとき、ワークフローが走って`backend`だけラベルを付与する流れを想定していました。

でも、 @takutok28 さんのおっしゃった内容で実装できるのであればお願いしたいです！

参考記事も載せておきます。
- https://docs.github.com/ja/actions/managing-issues-and-pull-requests/adding-labels-to-issues
