### ISSUE TITLE
issueのテンプレートを作成

### ISSUE THREAD

**Issue by aopontann** [qin-team-recipe/03-recipe-app-backend#6]
### 概要
作成したテンプレートを元にissueを作成するようにする

**Comment by aopontann** [comment]
### 参考になりそうな記事
- [GitHubのissue、こう書かれているとめちゃくちゃ嬉しい。良いissueの書き方とは](https://note.com/koushikagawa/n/n500e2f4d4019#2c0eba2e-130b-4b3a-95fd-3fce37bbfc96)

**Comment by aopontann** [comment]
必要であれば、プルリクのテンプレも作っていいかも！

**Comment by takutheking** [comment]
LGTM! こちらの記事を参考にシンプルに作って、開発中に変更しますか！
[Pull request テンプレート](https://dev.classmethod.jp/articles/pull-request-template/)だとこれ良さそうです！

**Comment by takutok28** [comment]
LGTM! こちらの記事を参考にシンプルに作って、開発中に変更しますか！
[Pull request テンプレート](https://dev.classmethod.jp/articles/pull-request-template/)だとこれ良さそうです！

**Comment by takutok28** [comment]
Closes #7
